import os
import re
import argparse
from datetime import datetime

# CONFIGURATION
VAULT_ROOT = r"C:\Users\Edward Magejo\OneDrive\Desktop\Antigravity\Control-Tower"
DAILY_NOTES_DIR = os.path.join(VAULT_ROOT, "00 - Pulse", "Daily Notes")
PROJECT_NAME = "SAMARIA"

def get_today_date():
    return datetime.now().strftime("%Y-%m-%d")

def patch_section(content, section_header, new_data):
    """
    Intelligently patches a section in a markdown file.
    If the section exists, it adds data after the header/description.
    """
    pattern = f"(## {section_header}.*?\n(> .*?\n)?)"
    replacement = r"\1" + new_data + "\n"
    
    if re.search(pattern, content):
        # Check if data already exists to avoid duplicates
        if new_data.strip() in content:
            return content
        return re.sub(pattern, replacement, content)
    else:
        # Section not found, append it
        return content + f"\n## {section_header}\n{new_data}\n"

def update_daily_note(summary=None, learnings=None, images=None):
    date_str = get_today_date()
    note_path = os.path.join(DAILY_NOTES_DIR, f"{date_str}.md")
    
    # 1. READ EXISTING OR USE TEMPLATE
    if os.path.exists(note_path):
        with open(note_path, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = f"""# 🛸 Daily Log: {date_str}

## 🎯 Primary Focus
- Continuous delivery of [[{PROJECT_NAME}]] architecture.

## 🧠 Captured Insights
> *Insights extracted autonomously during our collaboration.*

## 🔍 Deep Dives
> *Research synthesized by the browser subagent.*

## 🎨 Visual Artifacts
> *AI-generated imagery and UI concepts.*

## 🛠️ Technical Progress
### [[{PROJECT_NAME}]]

## 📬 Mental Model Backup
> *End-of-session state summary for next-session context restoration.*

---
*Generated by Antigravity OS*
"""

    # 2. PATCH DATA
    if summary:
        formatted_summary = f"### Session Summary\n- {summary}\n"
        content = patch_section(content, "🛠️ Technical Progress", formatted_summary)
    
    if learnings:
        formatted_learnings = f"- **KEY LEARNING**: {learnings}\n"
        content = patch_section(content, "🧠 Captured Insights", formatted_learnings)
        
    if images:
        image_list = images.split(",")
        formatted_images = "\n".join([f"![[{img.strip()}]]" for img in image_list])
        content = patch_section(content, "🎨 Visual Artifacts", formatted_images)

    # 3. WRITE BACK
    with open(note_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Patched daily note: {note_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--summary", help="Hi-level summary of accomplishments")
    parser.add_argument("--learnings", help="Key technical learnings")
    parser.add_argument("--images", help="Comma-separated list of image filenames in vault")
    args = parser.parse_args()
    
    update_daily_note(summary=args.summary, learnings=args.learnings, images=args.images)
